---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: nginx-default
    image: leandelivery/docker-systemd:ubuntu-18.04
    command: /sbin/init
    privileged: true
    tmpfs:
      - /sys/fs/cgroup
  - name: nginx-custom
    image: leandelivery/docker-systemd:ubuntu-18.04
    command: /sbin/init
    privileged: true
    tmpfs:
      - /sys/fs/cgroup
  - name: nginx-disabled
    image: leandelivery/docker-systemd:ubuntu-18.04
    command: /sbin/init
    privileged: true
    tmpfs:
      - /sys/fs/cgroup
provisioner:
  name: ansible
  inventory:
    host_vars:
      nginx-custom:
        nginx_keep_default_configs: true
        nginx_stable_repo: false
        nginx_logrotate_interval: weekly
        nginx_logrotate_backlog_size: 5
      nginx-disabled:
        nginx_systemd_setup: false
  playbooks:
    converge: ../resources/playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: ubuntu1804
verifier:
  name: testinfra
  lint:
    name: flake8
